### ISSUE TITLE
Minor problems with new render on documentation website

### ISSUE THREAD

**Issue by ACharbonneau** [nih-cfde/the-fair-cookbook#52]
There are a couple places where the render is slightly weird, and it's due to the little index pages:

- https://github.com/nih-cfde/the-fair-cookbook/blob/master/content/intro.md
- https://github.com/nih-cfde/the-fair-cookbook/blob/master/content/recipes/recipes-overview.md

see https://cfde-published-documentation.readthedocs-hosted.com/en/latest/the-fair-cookbook/

Basically, it's adding them as aTOC listing additional to the auto-generated one, so there's two of each, and the links within both those files are broken.

If you need these pages for the cookbook, it's fine to leave them, you just need to add a `.pages` file in the directory each one is in that specifies the folders it should render and leaves out that file. AwesomePages will ignore any files not listed in a `.pages` file if the `.pages` file exists. If you don't need them for the cookbook, just deleting those two pages fixes the render issue. 

The other thing I noticed is that in Governance, the ordering of the contents seems weird: "Intro" is second to last instead of first. This can also be fixed by specifying the order for files/folders in Governance with a `.pages` file.

I've written some more detailed instructions about how the system works at https://github.com/nih-cfde/published-documentation/blob/dev/README.md

**Comment by marisalim** [comment]
Hi! 

I noticed the left-side TOC on the [cookbook page](https://docs.nih-cfde.org/en/latest/the-fair-cookbook/) still has a few duplicate labels and pages to reorder (e.g., "Overview" should be the first header under "Recipes" and "Intro" the first under "Governance"):

<img width="1162" alt="Screen Shot 2021-02-09 at 3 11 32 PM" src="https://user-images.githubusercontent.com/5659802/107441514-34766d00-6aea-11eb-9faa-68a66cd02492.png">

I've made some of the edits in this PR: https://github.com/nih-cfde/the-fair-cookbook/pull/53

- added `.pages` to make Introduction landing page (this should get rid of the duplicate "Introduction" header)
- added `.pages` to "Governance" directory
- edited `.pages` to add "Overview" for recipes directory
    - added more page links to the recipes overview
- several page links were broken because they had `.html` instead of `.md` file extensions

#### A few questions:
- As far as I can tell, this [link](https://github.com/nih-cfde/the-fair-cookbook/blob/master/.pages) is rendering your Github README.md on the website's first cookbook [page](https://docs.nih-cfde.org/en/latest/the-fair-cookbook/) - is that on purpose? This page could certainly be part of the documentation, but the [introduction to FAIR](https://docs.nih-cfde.org/en/latest/the-fair-cookbook/content/Introduction/fair-principles/) material would make a better starting point.
- I wasn't sure what order the pages under "Governance" should be, just moved the "Intro" to the top. 
- There's a glossary under "Governance" that looks about the same as this [glossary on the website](https://docs.nih-cfde.org/en/latest/CFDE-glossary/) - is this a duplicate? It won't be rendered in the `.pages` file I made. Add it back if you'd like it rendered on the website!

I didn't add `.pages` to the other directories under "Recipes" in my PR, but if you'd like to order those pages, the format will be the same as the ones I've added. Let me know if you need help!

**Comment by marisalim** [comment]
I've fixed the render issues for the cookbook on the docs website - https://docs.nih-cfde.org/en/latest/the-fair-cookbook/intro/

There are lots of places where content probably needs to be updated, but the TOC structure is now in place!
